workspace:
  base: /go
  path: src/github.com/drone/drone-cache-lib

pipeline:
  deps:
    image: golang:1.10
    pull: true
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure

  test:
    image: golang:1.10
    pull: true
    commands:
      - go vet ./...
      - go test -cover ./...
